export { default as Donasi } from './Donasi';
export { default as DonasiPage } from './DonasiPage';
export { default as Edukasi } from './Edukasi';
export { default as Pengaduan } from './Pengaduan';
export { default as DaftarPengaduan } from './DaftarPengaduan';
export { default as Relawan } from './Relawan';
export { default as Poin } from './Poin';
export { default as Berita } from './Berita';
export { default as KebijakanPrivasi } from './KebijakanPrivasi';